name: db_covid19
channels:
  - conda-forge
  - defaults
dependencies:
  - make=4.3
  - nodejs=14.5.0
  - beautifulsoup4=4.9.1
  - dask=2.20.0
  - dask-labextension=2.0.2
  - geopandas=0.7.0
  - ipywidgets=7.5.1
  - jupyterlab=2.1.2
  - kaggle=1.5.6
  - line_profiler=3.0.2
  - matplotlib=3.2.1
  - memory_profiler=0.57.0
  - nltk=3.4.4
  - notebook=6.0.3
  - pandas=1.0.3
  - pip=20.1
  - pyarrow=0.17.1
  - pylint=2.5.3
  - pyjanitor=0.20.7
  - python=3.8.2
  - pyprojroot=0.2.0
  - pyyaml=5.3.1
  - seaborn=0.10.1
  - shapely=1.7.0
  - xlrd=1.2.0
  - pip:
    - ibm-watson==4.3.0
    - plotly==4.8.1
    - plotly-geo==1.0.0
    - pyshp==1.2.10
    - soupsieve==2.0
